version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    reviewers:
      - "msudgh"
    versioning-strategy: increase
    production-dependencies:
      applies-to: "security-updates"
      dependency-type: "production"
      time: "09:00"
      day: "sunday"
